services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: rh-azurite
    command: "azurite --loose --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rh-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SuaSenhaForte#2024"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  azurite-data:
  sqlserver-data:
